"""add tax_transactions and tax_calculations tables

Revision ID: 2ad556f2ed4a
Revises: c36fd2c29264
Create Date: 2026-04-18 10:36:18.117350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad556f2ed4a'
down_revision: Union[str, Sequence[str], None] = 'c36fd2c29264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sell_tx_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('sell_quantity', sa.Integer(), nullable=False),
    sa.Column('sell_price_krw', sa.Float(), nullable=False),
    sa.Column('acquisition_cost_krw', sa.Float(), nullable=False),
    sa.Column('commission_total_krw', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('gain_loss_krw', sa.Float(), nullable=False),
    sa.Column('trade_date', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_calculations', schema=None) as batch_op:
        batch_op.create_index('idx_tax_calc_symbol', ['symbol', 'year'], unique=False)
        batch_op.create_index('idx_tax_calc_year_method', ['year', 'method'], unique=False)

    op.create_table('tax_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_foreign', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('price_krw', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('commission_krw', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('trade_date', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('memo', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_tax_tx_source', ['source', 'source_order_id'], unique=False)
        batch_op.create_index('idx_tax_tx_symbol_date', ['symbol', 'trade_date'], unique=False)
        batch_op.create_index('idx_tax_tx_year', ['trade_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_tax_tx_year')
        batch_op.drop_index('idx_tax_tx_symbol_date')
        batch_op.drop_index('idx_tax_tx_source')

    op.drop_table('tax_transactions')
    with op.batch_alter_table('tax_calculations', schema=None) as batch_op:
        batch_op.drop_index('idx_tax_calc_year_method')
        batch_op.drop_index('idx_tax_calc_symbol')

    op.drop_table('tax_calculations')
    # ### end Alembic commands ###
