"""add advisory grade fields

Revision ID: 2e051b80939e
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 11:08:05.996464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e051b80939e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advisory_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('grade_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('composite_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('regime_alignment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('schema_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('value_trap_warning', sa.Boolean(), nullable=True))

    with op.batch_alter_table('portfolio_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weighted_grade_avg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('regime', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('schema_version', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_reports', schema=None) as batch_op:
        batch_op.drop_column('schema_version')
        batch_op.drop_column('regime')
        batch_op.drop_column('weighted_grade_avg')

    with op.batch_alter_table('advisory_reports', schema=None) as batch_op:
        batch_op.drop_column('value_trap_warning')
        batch_op.drop_column('schema_version')
        batch_op.drop_column('regime_alignment')
        batch_op.drop_column('composite_score')
        batch_op.drop_column('grade_score')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
