"""add ai_usage_log, ai_limits, audit_log tables

Revision ID: 9cda1c3787e5
Revises: de1f3d32fb96
Create Date: 2026-04-29 17:04:10.358634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cda1c3787e5'
down_revision: Union[str, Sequence[str], None] = 'de1f3d32fb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_limits_user_id'), ['user_id'], unique=True)

    op.create_table('ai_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_log_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_log_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('ai_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_log_date'))

    op.drop_table('ai_usage_log')
    with op.batch_alter_table('ai_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_limits_user_id'))

    op.drop_table('ai_limits')
    # ### end Alembic commands ###
