"""initial schema

Revision ID: cd83884bc87e
Revises: 
Create Date: 2026-04-04 14:47:12.631041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd83884bc87e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_cache',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('fundamental', sa.JSON(), nullable=True),
    sa.Column('technical', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'market')
    )
    op.create_table('advisory_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisory_reports', schema=None) as batch_op:
        batch_op.create_index('idx_advisory_reports_code_market', ['code', 'market', sa.literal_column('generated_at DESC')], unique=False)

    op.create_table('advisory_stocks',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('added_date', sa.String(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'market')
    )
    op.create_table('macro_gpt_cache',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('date_kst', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category', 'date_kst')
    )
    op.create_table('market_board_order',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'market')
    )
    op.create_table('market_board_stocks',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('added_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'market')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(), nullable=True),
    sa.Column('org_no', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.String(), nullable=False),
    sa.Column('filled_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('kis_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_orders_order_no_market', ['order_no', 'market'], unique=False)
        batch_op.create_index('idx_orders_status', ['status'], unique=False)
        batch_op.create_index('idx_orders_symbol_market', ['symbol', 'market', sa.literal_column('placed_at DESC')], unique=False)

    op.create_table('portfolio_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('condition_value', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_order_no', sa.String(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_info',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change_val', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('mktcap', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('high_52', sa.Float(), nullable=True),
    sa.Column('low_52', sa.Float(), nullable=True),
    sa.Column('price_updated_at', sa.String(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('pbr', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('dividend_per_share', sa.Float(), nullable=True),
    sa.Column('market_type', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('metrics_updated_at', sa.String(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('operating_income', sa.Integer(), nullable=True),
    sa.Column('net_income', sa.Integer(), nullable=True),
    sa.Column('bsns_year', sa.Integer(), nullable=True),
    sa.Column('fin_updated_at', sa.String(), nullable=True),
    sa.Column('return_3m', sa.Float(), nullable=True),
    sa.Column('return_6m', sa.Float(), nullable=True),
    sa.Column('return_1y', sa.Float(), nullable=True),
    sa.Column('returns_updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'market')
    )
    with op.batch_alter_table('stock_info', schema=None) as batch_op:
        batch_op.create_index('idx_stock_info_price_updated', ['price_updated_at'], unique=False)

    op.create_table('watchlist',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('added_date', sa.String(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'market')
    )
    op.create_table('watchlist_order',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'market')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_order')
    op.drop_table('watchlist')
    with op.batch_alter_table('stock_info', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_info_price_updated')

    op.drop_table('stock_info')
    op.drop_table('reservations')
    op.drop_table('portfolio_reports')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_orders_symbol_market')
        batch_op.drop_index('idx_orders_status')
        batch_op.drop_index('idx_orders_order_no_market')

    op.drop_table('orders')
    op.drop_table('market_board_stocks')
    op.drop_table('market_board_order')
    op.drop_table('macro_gpt_cache')
    op.drop_table('advisory_stocks')
    with op.batch_alter_table('advisory_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_advisory_reports_code_market')

    op.drop_table('advisory_reports')
    op.drop_table('advisory_cache')
    # ### end Alembic commands ###
