"""add tax_fifo_lots table

Revision ID: dedd740ad435
Revises: 2ad556f2ed4a
Create Date: 2026-04-18 14:59:05.491930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedd740ad435'
down_revision: Union[str, Sequence[str], None] = '2ad556f2ed4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_fifo_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('sell_tx_id', sa.Integer(), nullable=False),
    sa.Column('buy_tx_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buy_price_krw', sa.Float(), nullable=True),
    sa.Column('buy_trade_date', sa.String(), nullable=True),
    sa.Column('cost_krw', sa.Float(), nullable=True),
    sa.Column('warning', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_fifo_lots', schema=None) as batch_op:
        batch_op.create_index('idx_fifo_lot_buy', ['buy_tx_id'], unique=False)
        batch_op.create_index('idx_fifo_lot_calc', ['calculation_id'], unique=False)
        batch_op.create_index('idx_fifo_lot_sell', ['sell_tx_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_fifo_lots', schema=None) as batch_op:
        batch_op.drop_index('idx_fifo_lot_sell')
        batch_op.drop_index('idx_fifo_lot_calc')
        batch_op.drop_index('idx_fifo_lot_buy')

    op.drop_table('tax_fifo_lots')
    # ### end Alembic commands ###
