"""add params_json and strategy_display_name to backtest_jobs

Revision ID: ebdfc36d2ef3
Revises: dedd740ad435
Create Date: 2026-04-19 17:59:20.904213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdfc36d2ef3'
down_revision: Union[str, Sequence[str], None] = 'dedd740ad435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('strategy_display_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.drop_column('strategy_display_name')
        batch_op.drop_column('params_json')

    # ### end Alembic commands ###
