"""Add report tables: recommendation_history, macro_regime_history, daily_reports

Revision ID: f717b65d0d31
Revises: cd83884bc87e
Create Date: 2026-04-10 16:15:10.447237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f717b65d0d31'
down_revision: Union[str, Sequence[str], None] = 'cd83884bc87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('candidates_count', sa.Integer(), nullable=True),
    sa.Column('recommended_count', sa.Integer(), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('telegram_sent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index('idx_daily_reports_date_market', ['date', 'market'], unique=False)

    op.create_table('macro_regime_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('regime', sa.String(), nullable=False),
    sa.Column('buffett_ratio', sa.Float(), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('fear_greed_score', sa.Float(), nullable=True),
    sa.Column('kospi', sa.Float(), nullable=True),
    sa.Column('sp500', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('macro_regime_history', schema=None) as batch_op:
        batch_op.create_index('idx_macro_regime_date', ['date'], unique=False)

    op.create_table('recommendation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('regime', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('graham_number', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('safety_grade', sa.String(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('recommended_qty', sa.Integer(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('closed_at', sa.String(), nullable=True),
    sa.Column('closed_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_history', schema=None) as batch_op:
        batch_op.create_index('idx_rec_hist_code', ['code', 'market'], unique=False)
        batch_op.create_index('idx_rec_hist_market_date', ['market', 'created_at'], unique=False)
        batch_op.create_index('idx_rec_hist_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_history', schema=None) as batch_op:
        batch_op.drop_index('idx_rec_hist_status')
        batch_op.drop_index('idx_rec_hist_market_date')
        batch_op.drop_index('idx_rec_hist_code')

    op.drop_table('recommendation_history')
    with op.batch_alter_table('macro_regime_history', schema=None) as batch_op:
        batch_op.drop_index('idx_macro_regime_date')

    op.drop_table('macro_regime_history')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_reports_date_market')

    op.drop_table('daily_reports')
    # ### end Alembic commands ###
